version: '3'

networks:
  laravel:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
  nginx:
    image: laravel-nginx:1.19.3
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    container_name: nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/${APP_ENV}/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mariadb:10.5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - laravel
    volumes:
      - mysql:/var/lib/mysql/

  php:
    image: laravel-php:7.4-alpine
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/php/${APP_ENV}/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: laravel-composer:latest
    build:
      context: .
      dockerfile: docker/composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    user: laravel
    depends_on:
      - php
    networks:
      - laravel
    entrypoint: ['composer']

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    image: laravel-php:7.4-alpine
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    user: laravel
    depends_on:
      - mysql
      - composer
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
